### ISSUE TITLE
Why after I ran the script Is not closed?

### ISSUE THREAD

**Issue by TUNA-NOPE** [CriticalElement/spotify-free-api-player#1]
Why after I ran the script Is not closed?

**Comment by CriticalElement** [comment]
The spotify player is still listening to events from spotify through the websocket. You can call the disconnect method on the instance of the spotify player class to disconnect the websocket. Make sure you download the latest file from the latest commit.

**Comment by TUNA-NOPE** [comment]
Ok thanks
