### ISSUE TITLE
Many errors in experminental.py

### ISSUE THREAD

**Issue by ThatOneDev78601** [CriticalElement/spotify-free-api-player#5]
Hey, it seems I cannot get this working, is this outdated now?
I would like to contact you about this however it seems there is no contact info on your profile

**Comment by CriticalElement** [comment]
There was a breaking change a few months ago with the Spotify api, let me fix this in a couple hours

**Comment by ThatOneDev78601** [comment]
okay thanks, let me know if you were able to fix it, appreciated btw

**Comment by CriticalElement** [comment]
yeah, i just have a lot of schoolwork lol
definitely will get it fixed in like 6-8 hours

**Comment by ThatOneDev78601** [comment]
Ye np me too lol, using this GitHub for a school project of mine too lol. Np though there isn’t any apparent due date Sent from Mail for Windows From: CriticalElementSent: Tuesday, February 28, 2023 11:35 AMTo: CriticalElement/spotify-free-api-playerCc: ThatOneDev; AuthorSubject: Re: [CriticalElement/spotify-free-api-player] Many errors in experminental.py (Issue #5) yeah, i just have a lot of schoolwork loldefinitely will get it fixed in like 6-8 hours—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by CriticalElement** [comment]
hey, just got around to updating the code, and it should work for you now
if it doesn't, try relogging in to "open.spotify.com" using a web browser (google chrome, edge, firefox) and make sure to check the "remember me" option

**Comment by ThatOneDev78601** [comment]
Alright thanks so much, I gotta finish hw right now but ill let u know if it works tomorrow morning (EST for me) Sent from Mail for Windows From: CriticalElementSent: Tuesday, February 28, 2023 7:38 PMTo: CriticalElement/spotify-free-api-playerCc: ThatOneDev; AuthorSubject: Re: [CriticalElement/spotify-free-api-player] Many errors in experminental.py (Issue #5) hey, just got around to updating the code, and it should work for you nowif it doesn't, try relogging in to "open.spotify.com" using a web browser (google chrome, edge, firefox) and make sure to check the "remember me" option—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ThatOneDev78601** [comment]
![image](https://user-images.githubusercontent.com/73660853/222020624-917dc86b-4e2f-40ab-8451-59a5bf8339ca.png)
same errors as before, maybe I'm doing something wrong?
running the code with 

```
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)-8s - %(name)-14s - %(message)s')

spotifyplayer = SpotifyPlayer()
spotifyplayer.command(spotifyplayer.play('5wilF6g0r4VpNqQsV8fWKr'))
```

**Comment by ThatOneDev78601** [comment]
Also, might be worth noting that I'm using opera gx, not google chrome. Not sure if thats the issue though as opera uses chromium internally and it still uses chrome dev tools and all

**Comment by CriticalElement** [comment]
big oversight by me, try changing the `browser_cookie3.chrome()`  call to `browser_cookie3.opera_gx()` in `experimental.py`

![Screenshot_20230228-202457-035.png](https://user-images.githubusercontent.com/50345351/222029164-f9309156-aa66-47c2-bccb-49bfd3fe5d22.png)

**Comment by ThatOneDev78601** [comment]
![image](https://user-images.githubusercontent.com/73660853/222121980-c0647acb-de49-46cd-b521-c76bd39546d5.png)
there was no function named opera_gx() however there was one named opera() so i tried that, doing so resulted in this error

**Comment by ThatOneDev78601** [comment]
OH, i also use microsoft edge, and tried changing it from opera to edge, and now it works! thanks so much for the fix

**Comment by ThatOneDev78601** [comment]
not sure why opera doesnt work though, might just be bugged

**Comment by CriticalElement** [comment]
try reinstalling requirements with `pip install -U -r requirements.txt`

this could fix the opera gx problem

**Comment by ThatOneDev78601** [comment]
okay
